apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app 
  template:
    metadata:
      labels:
        app: node-app 
    spec:
      containers:
      - name: node-web-app 
        image: vlad/node-web-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8080 

